-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "surname" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "telephone" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "meta" JSONB;
